### ISSUE TITLE
Interactive Director: Added commands don't display correctly on list + exception when removing them

### ISSUE THREAD

**Issue by Kuroonehalf** [renpy/renpy#1267]
I mentioned this in the IRC the other day, and thought it might be related to the problem from the last thread, but it's persisted after that issue was fixed so it seems it's a different bug.

When I add a new command using the interactive director, a new line will show up on the list of commands, but it won't display the text saying what it is. Here's what that looks like:
![test_project1_-_autoreload_2017_10_06](https://user-images.githubusercontent.com/12227163/31281095-5c7d5b90-aaa6-11e7-8db8-61e2dc34c703.png)

Additionally, if I then try to remove that line, I get the following exception:
```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 27, in script
    e "You've created a new Ren'Py game."
  File "renpy/common/00director.rpy", line 1279, in event
    rv = self.child.event(ev, x, y, st)
  File "renpy/common/00director.rpy", line 1248, in __call__
    renpy.scriptedit.remove_line(state.filename, state.linenumber)
KeyError: (u'lib/windows-i686/game/script.rpy', 27)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 27, in script
    e "You've created a new Ren'Py game."
  File "C:\Users\Kuro\Desktop\Renpy\renpy\ast.py", line 624, in execute
    renpy.exports.say(who, what, interact=self.interact, *args, **kwargs)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\exports.py", line 1158, in say
    who(what, *args, **kwargs)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\character.py", line 911, in __call__
    self.do_display(who, what, cb_args=self.cb_args, **display_args)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\character.py", line 747, in do_display
    **display_args)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\character.py", line 523, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\ui.py", line 287, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\core.py", line 2553, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\core.py", line 3237, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\screen.py", line 653, in event
    rv = self.child.event(ev, x, y, st)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "renpy/common/00director.rpy", line 1279, in event
    rv = self.child.event(ev, x, y, st)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 232, in event
    rv = d.event(ev, x - xo, y - yo, st)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\behavior.py", line 897, in event
    return handle_click(self.clicked)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\behavior.py", line 832, in handle_click
    rv = run(action)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\behavior.py", line 306, in run
    return action(*args, **kwargs)
  File "renpy/common/00director.rpy", line 1248, in __call__
    renpy.scriptedit.remove_line(state.filename, state.linenumber)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\scriptedit.py", line 169, in remove_line
    line = lines[filename, linenumber]
KeyError: (u'lib/windows-i686/game/script.rpy', 27)

Windows-8-6.2.9200
Ren'Py 6.99.13.2834
test_project1 1.0
```

**Comment by Kuroonehalf** [comment]
Now I'm getting the following exception when I try to add any command (triggers after I press the Add button):
```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 27, in script
    e "Once you add a story, pictures, and music, you can release it to the world!"
  File "renpy/common/00director.rpy", line 1279, in event
    rv = self.child.event(ev, x, y, st)
  File "renpy/common/00director.rpy", line 1170, in __call__
    renpy.scriptedit.insert_line_before(statement, state.filename, state.linenumber)
Exception: The compile flag must have been given for script editing to work.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 27, in script
    e "Once you add a story, pictures, and music, you can release it to the world!"
  File "C:\Users\Kuro\Desktop\Renpy\renpy\ast.py", line 624, in execute
    renpy.exports.say(who, what, interact=self.interact, *args, **kwargs)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\exports.py", line 1158, in say
    who(what, *args, **kwargs)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\character.py", line 911, in __call__
    self.do_display(who, what, cb_args=self.cb_args, **display_args)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\character.py", line 747, in do_display
    **display_args)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\character.py", line 523, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\ui.py", line 287, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\core.py", line 2553, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\core.py", line 3237, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\screen.py", line 653, in event
    rv = self.child.event(ev, x, y, st)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "renpy/common/00director.rpy", line 1279, in event
    rv = self.child.event(ev, x, y, st)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 232, in event
    rv = d.event(ev, x - xo, y - yo, st)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\behavior.py", line 897, in event
    return handle_click(self.clicked)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\behavior.py", line 832, in handle_click
    rv = run(action)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\behavior.py", line 306, in run
    return action(*args, **kwargs)
  File "renpy/common/00director.rpy", line 1170, in __call__
    renpy.scriptedit.insert_line_before(statement, state.filename, state.linenumber)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\scriptedit.py", line 150, in insert_line_before
    raise Exception("The compile flag must have been given for script editing to work.")
Exception: The compile flag must have been given for script editing to work.

Windows-8-6.2.9200
Ren'Py 6.99.13.2846
test_project1 1.0
```

**Comment by renpytom** [comment]
Please use the nightly, as this has been fixed there.

**Comment by Kuroonehalf** [comment]
I have been using nightly. I updated right before running the tests and writing about them above.

Also, I hate to keep bothering you, but I just updated to the new nightly that's out and it's still not working right for me. Now, in adding a show command, when I click the attribute I get the following exception:

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 26, in script
    e "Once you add a story, pictures, and music, you can release it to the world!"
  File "renpy/common/00director.rpy", line 1283, in event
    rv = self.child.event(ev, x, y, st)
  File "renpy/common/00director.rpy", line 1062, in __call__
    update_ast()
  File "renpy/common/00director.rpy", line 442, in update_ast
    renpy.scriptedit.add_to_ast_before(statement, state.filename, linenumber)
Exception: Could not find unique first AST node.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 26, in script
    e "Once you add a story, pictures, and music, you can release it to the world!"
  File "C:\Users\Kuro\Desktop\Renpy\renpy\ast.py", line 624, in execute
    renpy.exports.say(who, what, interact=self.interact, *args, **kwargs)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\exports.py", line 1158, in say
    who(what, *args, **kwargs)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\character.py", line 911, in __call__
    self.do_display(who, what, cb_args=self.cb_args, **display_args)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\character.py", line 747, in do_display
    **display_args)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\character.py", line 523, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\ui.py", line 287, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\core.py", line 2553, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\core.py", line 3237, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\screen.py", line 653, in event
    rv = self.child.event(ev, x, y, st)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "renpy/common/00director.rpy", line 1283, in event
    rv = self.child.event(ev, x, y, st)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 232, in event
    rv = d.event(ev, x - xo, y - yo, st)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 232, in event
    rv = d.event(ev, x - xo, y - yo, st)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 232, in event
    rv = d.event(ev, x - xo, y - yo, st)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\viewport.py", line 300, in event
    rv = super(Viewport, self).event(ev, x, y, st)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 232, in event
    rv = d.event(ev, x - xo, y - yo, st)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\behavior.py", line 897, in event
    return handle_click(self.clicked)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\behavior.py", line 832, in handle_click
    rv = run(action)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\behavior.py", line 306, in run
    return action(*args, **kwargs)
  File "renpy/common/00director.rpy", line 1062, in __call__
    update_ast()
  File "renpy/common/00director.rpy", line 442, in update_ast
    renpy.scriptedit.add_to_ast_before(statement, state.filename, linenumber)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\scriptedit.py", line 298, in add_to_ast_before
    old, _ = first_and_last_nodes(nodes)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\scriptedit.py", line 264, in first_and_last_nodes
    raise Exception("Could not find unique first AST node.")
Exception: Could not find unique first AST node.

Windows-8-6.2.9200
Ren'Py 6.99.13.2852
test_project1 1.0
```

**Comment by renpytom** [comment]
Can you give me the sequence of events you use to reproduce these? Some of these tracebacks seem a little impossible to me in the current versions of Ren'Py - the errors make sense in the older version, but you shouldn't be able to open the editor on a line if there isn't a unique AST node associated with it.

**Comment by Kuroonehalf** [comment]
Sure. I am writing this while up to date with the latest nightly version.

Here's the project I'm using. It's a new project where I just imported Eileen's concerned sprite from the tutorial.
[test_project1.zip](https://github.com/renpy/renpy/files/1370610/test_project1.zip)

The steps I take:
- Launch game from the renpy launcher.
- On the main menu click "Start".
- Press "D" to bring up the interactive director.
- Click the "+" sign between script.rpy:0006 and script.rpy:0008.
- Under "Statement", click "show".
- Under "Attributes", click "concerned".
And I get an exception screen with the following text:

```

I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 9, in script
    e "Once you add a story, pictures, and music, you can release it to the world!"
  File "renpy/common/00director.rpy", line 1283, in event
    rv = self.child.event(ev, x, y, st)
  File "renpy/common/00director.rpy", line 1062, in __call__
    update_ast()
  File "renpy/common/00director.rpy", line 442, in update_ast
    renpy.scriptedit.add_to_ast_before(statement, state.filename, linenumber)
Exception: Could not find unique first AST node.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 9, in script
    e "Once you add a story, pictures, and music, you can release it to the world!"
  File "C:\Users\Kuro\Desktop\Renpy\renpy\ast.py", line 624, in execute
    renpy.exports.say(who, what, interact=self.interact, *args, **kwargs)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\exports.py", line 1158, in say
    who(what, *args, **kwargs)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\character.py", line 911, in __call__
    self.do_display(who, what, cb_args=self.cb_args, **display_args)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\character.py", line 747, in do_display
    **display_args)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\character.py", line 523, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\ui.py", line 287, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\core.py", line 2553, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\core.py", line 3237, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\screen.py", line 653, in event
    rv = self.child.event(ev, x, y, st)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "renpy/common/00director.rpy", line 1283, in event
    rv = self.child.event(ev, x, y, st)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 232, in event
    rv = d.event(ev, x - xo, y - yo, st)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 232, in event
    rv = d.event(ev, x - xo, y - yo, st)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 232, in event
    rv = d.event(ev, x - xo, y - yo, st)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\viewport.py", line 300, in event
    rv = super(Viewport, self).event(ev, x, y, st)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 232, in event
    rv = d.event(ev, x - xo, y - yo, st)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\behavior.py", line 897, in event
    return handle_click(self.clicked)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\behavior.py", line 832, in handle_click
    rv = run(action)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\behavior.py", line 306, in run
    return action(*args, **kwargs)
  File "renpy/common/00director.rpy", line 1062, in __call__
    update_ast()
  File "renpy/common/00director.rpy", line 442, in update_ast
    renpy.scriptedit.add_to_ast_before(statement, state.filename, linenumber)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\scriptedit.py", line 298, in add_to_ast_before
    old, _ = first_and_last_nodes(nodes)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\scriptedit.py", line 264, in first_and_last_nodes
    raise Exception("Could not find unique first AST node.")
Exception: Could not find unique first AST node.

Windows-8-6.2.9200
Ren'Py 6.99.13.2860
test_project1 1.0

```

**Comment by renpytom** [comment]
This appears to be fixed in the current build.

**Comment by Kuroonehalf** [comment]
Hm, I just updated, force recompiled, and tried again, and I still seem to be getting the exact same exception. :<

Here:

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 9, in script
    e "Once you add a story, pictures, and music, you can release it to the world!"
  File "renpy/common/00director.rpy", line 1283, in event
    rv = self.child.event(ev, x, y, st)
  File "renpy/common/00director.rpy", line 1062, in __call__
    update_ast()
  File "renpy/common/00director.rpy", line 442, in update_ast
    renpy.scriptedit.add_to_ast_before(statement, state.filename, linenumber)
Exception: Could not find unique first AST node.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 9, in script
    e "Once you add a story, pictures, and music, you can release it to the world!"
  File "C:\Users\Kuro\Desktop\Renpy\renpy\ast.py", line 624, in execute
    renpy.exports.say(who, what, interact=self.interact, *args, **kwargs)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\exports.py", line 1173, in say
    who(what, *args, **kwargs)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\character.py", line 911, in __call__
    self.do_display(who, what, cb_args=self.cb_args, **display_args)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\character.py", line 747, in do_display
    **display_args)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\character.py", line 523, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\ui.py", line 287, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\core.py", line 2553, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\core.py", line 3237, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\screen.py", line 653, in event
    rv = self.child.event(ev, x, y, st)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "renpy/common/00director.rpy", line 1283, in event
    rv = self.child.event(ev, x, y, st)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 232, in event
    rv = d.event(ev, x - xo, y - yo, st)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 232, in event
    rv = d.event(ev, x - xo, y - yo, st)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 232, in event
    rv = d.event(ev, x - xo, y - yo, st)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\viewport.py", line 300, in event
    rv = super(Viewport, self).event(ev, x, y, st)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 232, in event
    rv = d.event(ev, x - xo, y - yo, st)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\layout.py", line 969, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\behavior.py", line 897, in event
    return handle_click(self.clicked)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\behavior.py", line 832, in handle_click
    rv = run(action)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\display\behavior.py", line 306, in run
    return action(*args, **kwargs)
  File "renpy/common/00director.rpy", line 1062, in __call__
    update_ast()
  File "renpy/common/00director.rpy", line 442, in update_ast
    renpy.scriptedit.add_to_ast_before(statement, state.filename, linenumber)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\scriptedit.py", line 298, in add_to_ast_before
    old, _ = first_and_last_nodes(nodes)
  File "C:\Users\Kuro\Desktop\Renpy\renpy\scriptedit.py", line 264, in first_and_last_nodes
    raise Exception("Could not find unique first AST node.")
Exception: Could not find unique first AST node.

Windows-8-6.2.9200
Ren'Py 6.99.13.2881
test_project1 1.0
```

Is there perhaps an even more recent version that I have to wait a bit before I can update, or this is it?

Also, are there other ways I can help you diagnose the problem?

**Comment by renpytom** [comment]
I don't know if there is a way. It's been working for me. I think you need to start with a clean nightly or something - as it's fixed here, doing exactly what you say.

**Comment by Kuroonehalf** [comment]
Ah! I redownloaded renpy, updated it to the nightly version, and ran that, and indeed, I get no issues with this one.

Strange why the old SDK is not working and this one works. Shouldn't all the files have been updated to be the same as the new SDK? I wonder if this affecting other people too. Might be worth looking into. Otherwise, it seems this issue is solved. Thank you.

**Comment by arowana-vx** [comment]
Congrats on the new release! Unfortunately, I think I'm getting the same "Could not find unique first AST node" error mentioned above. 

The error appears whenever I try to select my final option. For example, start "The Question", click a "+", then try to do Show -> Attributes -> select any attribute. A exception message like this immediately pops up.
![image](https://user-images.githubusercontent.com/31723553/32208241-733eb8da-bdbe-11e7-823f-39cd11e567cb.png)

Weirdly, this only seems to be a problem on my Mac; I had no issues when I tried it on a PC. I used the new 6.99.13 official release (6.99.13.2919) for both, freshly downloaded from the website. Let me know if you need more details!

**Comment by elizagamedev** [comment]
Unfortunately I'm having the same issue in regards with crashing from `add_to_ast_before()`. From my brief testing it seems like the crash happens when `nodes_on_line()` can't find the currently edited node, so I assume that somehow the node gets completely deleted when editing it...

**Comment by arowana-vx** [comment]
@renpytom Not sure if you're still watching this issue, so sending you a note just in case you haven't seen the new comments.

**Comment by JWilson93** [comment]
Just changed to the nightly build and still encountering this issue with The Question on windows when trying to change the opening bg to meadow

[code]
I'm sorry, but an uncaught exception occurred.

While parsing game/script.rpy.
  File "game/script.rpy", line 20, in script
    
  File "renpy/common/00director.rpy", line 1303, in event
    rv = self.child.event(ev, x, y, st)
  File "renpy/common/00director.rpy", line 1072, in __call__
    update_ast()
  File "renpy/common/00director.rpy", line 456, in update_ast
    renpy.scriptedit.remove_from_ast(state.filename, linenumber)
Exception: Could not find unique first AST node.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 20, in script
    
  File "C:\Users\jacob\renpy-6.99.13-sdk\renpy\ast.py", line 643, in execute
    renpy.exports.say(who, what, interact=self.interact, *args, **kwargs)
  File "C:\Users\jacob\renpy-6.99.13-sdk\renpy\exports.py", line 1175, in say
    who(what, *args, **kwargs)
  File "C:\Users\jacob\renpy-6.99.13-sdk\renpy\character.py", line 1017, in __call__
    self.do_display(who, what, cb_args=self.cb_args, **display_args)
  File "C:\Users\jacob\renpy-6.99.13-sdk\renpy\character.py", line 821, in do_display
    **display_args)
  File "C:\Users\jacob\renpy-6.99.13-sdk\renpy\character.py", line 570, in display_say
    rv = renpy.ui.interact(mouse='say', type=type, roll_forward=roll_forward)
  File "C:\Users\jacob\renpy-6.99.13-sdk\renpy\ui.py", line 287, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\jacob\renpy-6.99.13-sdk\renpy\display\core.py", line 2609, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "C:\Users\jacob\renpy-6.99.13-sdk\renpy\display\core.py", line 3339, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "C:\Users\jacob\renpy-6.99.13-sdk\renpy\display\layout.py", line 979, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\jacob\renpy-6.99.13-sdk\renpy\display\layout.py", line 979, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\jacob\renpy-6.99.13-sdk\renpy\display\layout.py", line 979, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\jacob\renpy-6.99.13-sdk\renpy\display\screen.py", line 655, in event
    rv = self.child.event(ev, x, y, st)
  File "C:\Users\jacob\renpy-6.99.13-sdk\renpy\display\layout.py", line 979, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "renpy/common/00director.rpy", line 1303, in event
    rv = self.child.event(ev, x, y, st)
  File "C:\Users\jacob\renpy-6.99.13-sdk\renpy\display\layout.py", line 232, in event
    rv = d.event(ev, x - xo, y - yo, st)
  File "C:\Users\jacob\renpy-6.99.13-sdk\renpy\display\layout.py", line 979, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\jacob\renpy-6.99.13-sdk\renpy\display\layout.py", line 979, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\jacob\renpy-6.99.13-sdk\renpy\display\layout.py", line 232, in event
    rv = d.event(ev, x - xo, y - yo, st)
  File "C:\Users\jacob\renpy-6.99.13-sdk\renpy\display\layout.py", line 232, in event
    rv = d.event(ev, x - xo, y - yo, st)
  File "C:\Users\jacob\renpy-6.99.13-sdk\renpy\display\viewport.py", line 300, in event
    rv = super(Viewport, self).event(ev, x, y, st)
  File "C:\Users\jacob\renpy-6.99.13-sdk\renpy\display\layout.py", line 232, in event
    rv = d.event(ev, x - xo, y - yo, st)
  File "C:\Users\jacob\renpy-6.99.13-sdk\renpy\display\layout.py", line 979, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Users\jacob\renpy-6.99.13-sdk\renpy\display\behavior.py", line 897, in event
    return handle_click(self.clicked)
  File "C:\Users\jacob\renpy-6.99.13-sdk\renpy\display\behavior.py", line 832, in handle_click
    rv = run(action)
  File "C:\Users\jacob\renpy-6.99.13-sdk\renpy\display\behavior.py", line 306, in run
    return action(*args, **kwargs)
  File "renpy/common/00director.rpy", line 1072, in __call__
    update_ast()
  File "renpy/common/00director.rpy", line 456, in update_ast
    renpy.scriptedit.remove_from_ast(state.filename, linenumber)
  File "C:\Users\jacob\renpy-6.99.13-sdk\renpy\scriptedit.py", line 368, in remove_from_ast
    first, last = first_and_last_nodes(nodes)
  File "C:\Users\jacob\renpy-6.99.13-sdk\renpy\scriptedit.py", line 289, in first_and_last_nodes
    raise Exception("Could not find unique first AST node.")
Exception: Could not find unique first AST node.

Windows-8-6.2.9200
Ren'Py 6.99.14.3081
The Question Ren'Py 7 Edition
[/code]

**Comment by Gouvernathor** [comment]
This is probably not relevant anymore : it's been more than 5 years and some work has been done on the director recently-ish, so if this was still an active bug we would probably have noticed.
