### ISSUE TITLE
MatrixColor in transforms doesn't work properly

### ISSUE THREAD

**Issue by Inui-senpai** [renpy/renpy#3888]
Problem description: applied transformations with `matrixcolor` properties causes an exception in the latest stable version of Ren'Py (8.0.2.22081402): `TypeError: Argument 'other' has incorrect type (expected renpy.display.matrix.Matrix, got SaturationMatrix)`.
On the previous stable versions of Ren'Py (7.4.11, 8.0.0, 8.0.1) transforms with these properties works the way they should.

Steps to reproduce:
1. Define an image (not sure if it reproducible with any image, I used a screenshot via `FileTakeScreenshot()` function):
```renpy
image sample_image = "path/to/image.format"
```
2. Create a transform:
```renpy
transform sample_transform: # smooth transition to grayscale
    matrixcolor SaturationMatrix(1.0)
    linear 1.5 matrixcolor SaturationMatrix(0.0)
```
3. Apply transition to image:
```renpy
label start:
    show sample_image at sample_transform
    $ renpy.pause(hard=True)
```
4. ???
5. Profit!!1

Pinned traceback.txt was taken from my test project.

[traceback.txt](https://github.com/renpy/renpy/files/9388777/traceback.txt)

**Comment by Gouvernathor** [comment]
Seems fixed by eac73269de13d4f3329ce820012646a32e1833f6.
Can you try using the last nightly version ?

**Comment by Inui-senpai** [comment]
> Can you try using the last nightly version ?

On latest nightly version of 8th revision of Ren'Py (8.1.0.22082002n) transforms with `matrixcolor` properties works as in the previous stable versions.

**Comment by qTich** [comment]
I believe that not all changes are in the released version,
for example, there is no this commit (d88cefbdefea06049e61c5ec6c0ff0437694afba),
which is why there is an error.

**Comment by Gouvernathor** [comment]
@qTich no, we're talking about the Nightly version, not the Release version.
The nightly does have these two commits, see :
![image](https://user-images.githubusercontent.com/44340603/185792938-5b7c7bb4-8dc5-451f-92d6-460c241f9813.png)

@Inui-senpai I can't reproduce the bug on the last nightly (8.1.0.22082103n) with the code you're giving.

**Comment by qTich** [comment]
@Gouvernathor, he mentioned in the beginning `(8.0.2.22081402)` and I believe this is the released version.

**Comment by Gouvernathor** [comment]
Sure, and I'm saying this has been resolved since then.
@Inui-senpai if you meant that the nightly on your end doesn't raise the error, I believe we can close this. The fix will be in the next Release.

**Comment by Inui-senpai** [comment]
Yes, I meant that transforms with `matrixcolor` properties works on latest nightly version. And I think this Issue should be closed after the next stable version's release, because this bug, technically speaking, still persists.

**Comment by JiGSaWKilla89** [comment]
Can confirm `matrixcolor` working correctly in latest release 8.0.3.
