### ISSUE TITLE
Bugs since Ren'Py 8.3.4 (maybe earlier): buttons don't change their conditions, cursor behaves unpredictably, some letters become replaced with squares.

### ISSUE THREAD

**Issue by Al-the-Procrastinator** [renpy/renpy#6222]
**I really ask not to distribute / use the full code for moving eyes, which is used here, since it took me a lot of time and effort to get it to work, and I do not want it to be used by someone else before the release of my project.** If you need the base, here you are: https://lemmasoft.renai.us/forums/viewtopic.php?p=567062#p567062

As you asked, the test project:
[PROBLEMS.zip](https://github.com/user-attachments/files/19271572/PROBLEMS.zip)
I hope it isn't too heavy.

> Comments:
> 
> 1) The game should be played in fullscreen and 2x modes as sometimes behaviour might differ;
> 
> 2) Press "M" to enter the main menu while in game (I disabled right-click as it was misclicked often), press and hold "ESC" to close the game;
> 
> 3) If you are on the main menu for a long time, then the eyes will change color, don't be alarmed;
> 
> 4) The game's framerate is reduced to 30 fps as otherwise the screen started randomly flickering during the gameplay (even without all these animations and shaders). With 30 fps it also flickers sometimes if you press keys/buttons too often - this problem appears in earlier versions as well; 
> 
> 5) in Ren'Py 8.3.6 eyes, thankfully, don't frese (in Ren'Py 8.3.4 they do), but there is another problem related with the cursor itself (problem 2);
> 
> 6) Evetything (except for flickering) works pretty fine in Ren'Py 8.2.0 and earlier.
> 
> Problems:
> 
> 1) Buttons don't change their conditions when hovered/unhovered until you click them;
> 
> 2) Sometimes, even though the cursor is shown, it is being considered as hidden. Then it disappears and doesn't appear for some time when moved;
> 
> 3) I've just noticed that some letters are replaced with sqares, though there are no problems with the font itself. For example, in the preferences screen there are three "^" in a row, and the last one is a square for some reason.

**Comment by renpytom** [comment]
(1) I've been unable to repeat this in Ren'Py 8.3.7. As best I can tell, it's working - the eyes close when hovered/unhovered, when I put a hovered function on the start button, it triggers... it seems to work. 

(2) This is a feature - the mouse hides after 30 seconds without any motion, when the user is using auto-forward mode or a mouse.  You can disable it with:

```renpy
define config.mouse_hide_time = None
```

(3) Was a regression, and has been fixed.

**Comment by Al-the-Procrastinator** [comment]
Hello!
I know that hiding cursor is a feature, but, as I described in the additional file, it doesn't appear back sometimes though still recognised as shown. The eyes follow it, but it is invisible.
However, I'm glad that some problems was fixed, thank you! понедельник, 17 марта 2025г., 05:07 +03:00 от Tom Rothamel  ***@***.*** :

**Comment by Al-the-Procrastinator** [comment]
Hmm, that's weird. I've just updated to Ren'Py 8.4.0 and all the problems are still there, even hovering and uncovering works bad (but better than used to, thankfully!)
Added: opened the project once again, now hovering doesn't work. Well, I assume that's a problem with my PC... But it isn't that weak and slow. понедельник, 17 марта 2025г., 05:07 +03:00 от Tom Rothamel  ***@***.*** :

**Comment by Al-the-Procrastinator** [comment]
It might be so, but it's strange, because Ren'Py 8.2 and earlier works absolutely fine. Though, if this problem doesn't appear on your PC, it's alright then, I think. Just hope the end players of my project won't experience this bug as well as it ruins about 70% of the gameplay (I'm doing a point&click game). понедельник, 17 марта 2025г., 16:06 +03:00 от Tom Rothamel  ***@***.*** :
